### ISSUE TITLE
notify can hang when parsing

### ISSUE THREAD

**Issue by lucas8** [EvolutionaryLinguisticsAssociation/Babel2#7]
I noticed that in some situation calling ```comprehend``` would hang, and after looking into it, it seems that the last call to ```notify``` in the ```next-cip-solution``` function causes it.

**Comment by JensNevens** [comment]
Hello @lucas8 

Could you provide us with some more information, so we can better understand what is going on.

 - System information: what OS and Lisp implementation are you running?
 - Information about your grammar: how many constructions are there? Is this a hashed construction set?
 - Some more clarifications: what do you mean by _hang_. Does your Lisp freeze completely? Does `comprehend` take a few extra (milli)seconds? Does this occur when comprehending particular sentences or does it also occur for sentences that work fine otherwise? You mention this problem occurs _in some situations_; do you have additional information that will allow us to recreate this problem?

Thanks

**Comment by lucas8** [comment]
I am using linux with clozure CL 1.11.5. The grammar I use can be found [there](https://gist.github.com/lucas8/a4f8c9fa6cfd08f5948cbc96bb339a5e). In this case lisp freeze completely when comprehending ```'("breakfast")``` but not ```'("he")```. It also disapeared once when I added a lot of ```format``` in the code to track the issue.

**Comment by kbeuls** [comment]
Can you try this:
`(set-configuration (visualization-configuration *fcg-constructions*) :show-constructional-dependencies nil)`
The constructional dependencies is a feature that was only recently added, and is still rather experimental. Let me know if disabling it solves your problem.

**Comment by lucas8** [comment]
It does seem to fix the issue, thanks.
